# Generated by Django 6.0.1 on 2026-01-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transcripts', '0001_initial'),
        ('uploaded_files', '0003_uploadedfile_unique_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='project',
        ),
        migrations.AddField(
            model_name='transcript',
            name='uploaded_file',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transcripts',
                related_query_name='transcript',
                to='uploaded_files.uploadedfile',
                verbose_name='Uploaded file',
            ),
        ),
    ]
