# Generated by Django 6.0.1 on 2026-01-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transcripts', '0002_remove_transcript_project_transcript_uploaded_file'),
        ('uploaded_files', '0003_uploadedfile_unique_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='uploaded_file',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transcripts',
                related_query_name='transcript',
                to='uploaded_files.uploadedfile',
                verbose_name='Uploaded file',
            ),
        ),
    ]
