# Generated by Django 6.0.7 on 2026-07-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_alter_transcript_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='language',
        ),
    ]
