# Generated by Django 6.0.7 on 2026-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transcripts', '0004_remove_transcript_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
