# Generated by Django 6.0.7 on 2026-07-31 11:39

import mmt.transcripts.mmt_schema
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transcripts', '0005_transcript_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='content',
            field=models.JSONField(
                default=dict,
                help_text='Paste in the whole transcript in JSON format.',
                validators=[mmt.transcripts.mmt_schema.validate_mmt_content],
                verbose_name='Content',
            ),
        ),
    ]
