# Generated by Django 6.1.1 on 2026-10-04 18:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transcripts', '0007_rename_mention_label_to_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityExtractionJob',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Updated at'),
                ),
                (
                    'task_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name='Task ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('queued', 'Queued'),
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                        ],
                        default='queued',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                (
                    'result_transcript',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='transcripts.transcript',
                        verbose_name='Result transcript',
                    ),
                ),
                (
                    'transcript',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entity_extraction_jobs',
                        to='transcripts.transcript',
                        verbose_name='Transcript',
                    ),
                ),
            ],
            options={
                'verbose_name': 'entity extraction job',
                'verbose_name_plural': 'entity extraction jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
