# Generated by Django 5.2.3 on 2025-06-18 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload_jobs", "0002_alter_uploadjob_check_media_files_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadjob",
            options={
                "ordering": ["created_at"],
                "verbose_name": "upload job",
                "verbose_name_plural": "upload jobs",
            },
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated_at"),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
