# Generated by Django 5.2.5 on 2025-08-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_jobs', '0003_alter_uploadjob_options_alter_uploadjob_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadJob',
        ),
    ]
