#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-py-ner IMAGE"
    exit 1
}

image="$1"
container="mmt-py-ner"
echo "Running image $image as $container ..."

docker run \
       --network host \
       --restart always \
       --init \
       --detach \
       --memory 3000m \
       --memory-swap 3000m \
       --health-cmd 'nc -vz -w 2 localhost 8000' \
       --health-start-period 120s \
       --name="$container" \
       "$image"
