#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-py-web TAG"
    exit 1
}

tag="$1"
image="ghcr.io/asr4memory/mmt-py:$1"
container="mmt-py-web"
echo "Running image $image as $container ..."

docker run \
       --restart always \
	   --init \
	   --detach \
	   --env-file env.list \
	   --memory 1500m \
	   --memory-swap 1500m \
	   --health-cmd 'nc -vz -w 2 localhost 8000' \
	   --health-start-period 120s \
	   --publish 8000:8000 \
	   --volume /user_files_dir_on_server:/app/django-app/user_files \
	   --name="$container" \
	   "$image"
