#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-py-celery IMAGE"
    exit 1
}

image="$1"
container="mmt-py-celery"
echo "Running image $image as $container ..."

docker run \
       --network host \
       --restart always \
	   --init \
	   --detach \
	   --env-file env.list \
	   --health-cmd "celery inspect ping" \
	   --volume user_files:/app/django-app/user_files \
	   --name="$container" \
	   "$image" celery -A mmt worker -l INFO
