#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-py-web IMAGE"
    exit 1
}

image="$1"
container="mmt-py-web"
echo "Running image $image as $container ..."

docker run \
       --network host \
       --restart always \
	   --init \
	   --detach \
	   --env-file env.list \
	   --memory 1500m \
	   --memory-swap 1500m \
	   --health-cmd 'nc -vz -w 2 localhost 8000' \
	   --health-start-period 120s \
	   --volume user_files:/app/django-app/user_files \
	   --name="$container" \
	   "$image"
