[project]
name = "mmt-py"
version = "1.2.2"
description = "Python implementation of Media Management Tool"
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL"
license-files = ["LICENSE"]
dependencies = [
    "aiofiles~=24.1",
    "celery~=5.5",
    "django-allauth[socialaccount]~=65.0",
    "django-environ~=0.12",
    "django-htmx~=1.23",
    "django-json-widget~=2.0",
    "django-storages~=1.14",
    "django-vite~=3.1",
    "django-widget-tweaks~=1.5",
    "django~=5.2",
    "hypercorn~=0.17",
    "mysqlclient~=2.2",
    "redis~=6.2",
    "sentry-sdk[django]~=2.29",
    "watchdog~=6.0",
    "whitenoise~=6.9",
]

[dependency-groups]
dev = [
    "bpython>=0.25",
    "bs4>=0.0.2",
    "django-debug-toolbar~=5.2.0",
    "django-extensions~=4.1",
]
