#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-ner TAG"
    exit 1
}

image="ghcr.io/asr4memory/mmt-ner:$1"
container="mmt-ner"
ner_port="${MMT_NER_PORT:?set MMT_NER_PORT to the host port for the NER service}"
echo "Running image $image as $container ..."

podman run \
       --restart always \
       --init \
       --detach \
       --memory 3000m \
       --memory-swap 3000m \
       --health-cmd 'nc -vz -w 2 localhost 8000' \
       --health-start-period 120s \
       --publish "$ner_port:8000" \
       --name="$container" \
       "$image"
