#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-app-celery TAG"
    exit 1
}

image="ghcr.io/asr4memory/mmt-app:$1"
container="mmt-app-celery"
data_dir="${MMT_DATA_DIR:?set MMT_DATA_DIR to the host user-files directory}"
echo "Running image $image as $container ..."

podman run --restart always --init --detach \
	   --env-file env.list \
	   --workdir /app/django-app \
	   --memory 768m --memory-swap 1280m \
	   --cpu-shares 512 \
	   --health-cmd 'celery --app=mmt inspect ping --destination=celery@$(hostname)' \
	   --volume "$data_dir:/app/django-app/user_files" \
	   --name="$container" "$image" \
	   celery --app=mmt worker --hostname=celery@%h --concurrency=2 --beat --loglevel=INFO
