#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-app-media TAG"
    exit 1
}

image="ghcr.io/asr4memory/mmt-app:$1"
container="mmt-app-media"
data_dir="${MMT_DATA_DIR:?set MMT_DATA_DIR to the host user-files directory}"
echo "Running image $image as $container ..."

podman run --restart always --init --detach \
	   --env-file env.list \
	   --memory 1024m --memory-swap 1536m \
	   --cpu-shares 256 \
	   --health-cmd 'celery -A mmt inspect ping -d media@$HOSTNAME' \
	   --volume "$data_dir:/app/django-app/user_files" \
	   --name="$container" "$image" \
	   celery -A mmt worker -Q media -n media@%h -l INFO --concurrency=1
