#!/bin/bash

[[ $# -eq 1 ]] || {
    echo "usage: create-mmt-app-media TAG"
    exit 1
}

image="ghcr.io/asr4memory/mmt-app:$1"
container="mmt-app-media"
data_dir="${MMT_DATA_DIR:?set MMT_DATA_DIR to the host user-files directory}"
echo "Running image $image as $container ..."

podman run --restart always --init --detach \
	   --env-file env.list \
	   --workdir /app/django-app \
	   --memory 1024m --memory-swap 1536m \
	   --cpu-shares 256 \
	   --health-cmd 'celery --app=mmt inspect ping --destination=media@$(hostname)' \
	   --volume "$data_dir:/app/django-app/user_files" \
	   --name="$container" "$image" \
	   celery --app=mmt worker --queues=media --hostname=media@%h --concurrency=1 --loglevel=INFO
