# Generated by Django 5.2.6 on 2025-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploaded_files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="status",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="has_file",
            field=models.BooleanField(default=False, verbose_name="Has file"),
        ),
    ]
