# Generated by Django 5.2.3 on 2025-06-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "upload_jobs",
            "0003_alter_uploadjob_options_alter_uploadjob_created_at_and_more",
        ),
        ("uploaded_files", "0003_alter_uploadedfile_checksum_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "ordering": ["created_at", "filename"],
                "verbose_name": "uploaded file",
                "verbose_name_plural": "uploaded files",
            },
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="upload_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="upload_jobs.uploadjob",
                verbose_name="Upload job",
            ),
        ),
    ]
