# Generated by Django 6.0.2 on 2026-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploaded_files', '0003_uploadedfile_unique_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='waveform',
            field=models.JSONField(
                blank=True,
                help_text='Waveform data is created automatically with a background job.',
                null=True,
                verbose_name='Waveform',
            ),
        ),
    ]
