# Generated by Django 5.2.3 on 2025-06-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploaded_files", "0004_alter_uploadedfile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="chunk_count",
            field=models.IntegerField(default=0, verbose_name="Chunk count"),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="chunks_transferred",
            field=models.IntegerField(default=0, verbose_name="Chunks transferred"),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("uploading", "Uploading"),
                    ("complete", "Complete"),
                    ("corrupt", "Corrupt"),
                    ("missing", "Missing"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
