# Generated by Django 6.0.2 on 2026-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploaded_files', '0004_uploadedfile_waveform'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='duration',
            field=models.IntegerField(
                default=0,
                help_text='Duration is calculated automatically with a background job.',
                verbose_name='Duration',
            ),
        ),
    ]
