# Generated by Django 5.2.3 on 2025-06-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0005_uploadedfile_chunk_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('uploading', 'Uploading'), ('complete', 'Complete'), ('corrupt', 'Corrupt'), ('missing', 'Missing')], default='created', max_length=20, verbose_name='Status'),
        ),
    ]
