# Generated by Django 5.2.4 on 2025-07-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_options"),
        ("uploaded_files", "0005_uploadedfile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="upload_job",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
    ]
