# Generated by Django 6.0.2 on 2026-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploaded_files', '0005_uploadedfile_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='waveform_sampling_rate',
            field=models.IntegerField(
                default=0,
                help_text='Sampling rate of the waveform in Hertz (Hz).',
                verbose_name='Waveform sampling rate',
            ),
        ),
    ]
