# Generated by Django 5.2.4 on 2025-07-25 07:23

from django.db import migrations


def delete_some_rows(apps, scheme_editor):
    model = apps.get_model("uploaded_files", "UploadedFile")
    model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("uploaded_files", "0006_remove_uploadedfile_upload_job_uploadedfile_project"),
    ]

    operations = [migrations.RunPython(delete_some_rows)]
