# Generated by Django 6.0.5 on 2026-05-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0006_uploadedfile_waveform_sampling_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='transferred',
        ),
    ]
