# Generated by Django 5.2.3 on 2025-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploaded_files", "0006_alter_uploadedfile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="chunk_count",
            field=models.IntegerField(default=1, verbose_name="Chunk count"),
        ),
    ]
