# Generated by Django 6.0.5 on 2026-05-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploaded_files', '0006_uploadedfile_waveform_sampling_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('index', models.PositiveIntegerField()),
                (
                    'uploaded_file',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chunks',
                        to='uploaded_files.uploadedfile',
                    ),
                ),
            ],
            options={
                'ordering': ['index'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('uploaded_file', 'index'), name='unique_chunk'
                    )
                ],
            },
        ),
    ]
