# Generated by Django 6.0.5 on 2026-05-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploaded_files', '0007_remove_uploadedfile_transferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='waveform',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='waveform_sampling_rate',
        ),
        migrations.CreateModel(
            name='Waveform',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.JSONField(verbose_name='Data')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Updated at'),
                ),
                (
                    'uploaded_file',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='waveform',
                        to='uploaded_files.uploadedfile',
                        verbose_name='Uploaded file',
                    ),
                ),
            ],
            options={
                'verbose_name': 'waveform',
                'verbose_name_plural': 'waveforms',
            },
        ),
    ]
