# Generated by Django 6.0.5 on 2026-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0007_filechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechunk',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
