# Generated by Django 5.2.4 on 2025-07-25 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_options"),
        ("uploaded_files", "0007_auto_20250725_0723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
    ]
