# Generated by Django 6.0.5 on 2026-05-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0007_remove_uploadedfile_transferred'),
        ('uploaded_files', '0008_filechunk_checksum'),
    ]

    operations = [
    ]
