# Generated by Django 6.0.5 on 2026-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploaded_files', '0009_merge_20260508_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(
                blank=True, default='', max_length=255, verbose_name='Original filename'
            ),
        ),
    ]
