# Generated by Django 6.0.5 on 2026-06-01 15:10

from django.db import migrations, models
from django.db.models import F


def backfill_original_filename(apps, schema_editor):
    UploadedFile = apps.get_model('uploaded_files', 'UploadedFile')
    UploadedFile.objects.filter(original_filename='').update(
        original_filename=F('filename')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0009_filechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(default='', max_length=255, verbose_name='Original filename'),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_original_filename, migrations.RunPython.noop),
    ]
