# Generated by Django 6.0.6 on 2026-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0011_remove_filechunk_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='assembling',
            field=models.BooleanField(default=False, verbose_name='Assembling'),
        ),
    ]
