# Generated by Django 6.0.7 on 2026-07-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0012_uploadedfile_assembling'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='has_web_video',
            field=models.BooleanField(default=False, help_text='A 480p web-friendly version is generated automatically with a background job for videos.', verbose_name='Has web video'),
        ),
    ]
