# Generated by Django 6.0.7 on 2026-07-31 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploaded_files', '0013_uploadedfile_has_web_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechunk',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Created at',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filechunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
