# Generated by Django 5.2.4 on 2025-07-25 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
