# Generated by Django 5.2.6 on 2025-09-30 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0005_alter_processingrequest_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
