# Generated by Django 5.2.7 on 2025-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='created', max_length=20, verbose_name='Status')),
                ('admin_comment', models.TextField(blank=True, default='', help_text='Optional comment by the administrator reviewing this request.', verbose_name='Admin comment')),
                ('language', models.CharField(blank=True, default='', max_length=255, verbose_name='Language')),
                ('make_available_on_platform', models.BooleanField(default=False, verbose_name='Make available on platform')),
                ('transcribe', models.BooleanField(default=False, verbose_name='Transcribe')),
                ('check_media_files', models.BooleanField(default=False, verbose_name='Check media files')),
                ('replace_existing_files', models.BooleanField(default=False, verbose_name='Replace existing files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', related_query_name='service_request', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'service request',
                'verbose_name_plural': 'service requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProcessingRequest',
        ),
    ]
