# Generated by Django 5.2.7 on 2025-10-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_processingrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrequest',
            name='uploaded_files',
            field=models.JSONField(default=list, verbose_name='Uploaded files'),
        ),
    ]
