# Generated by Django 5.2.8 on 2025-11-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_processingrequest_one_action_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingrequest',
            name='check_media_files',
            field=models.BooleanField(default=False, verbose_name='Check media files'),
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('nl', 'Dutch'), ('uk', 'Ukrainian'), ('pt', 'Portuguese'), ('ar', 'Arabic'), ('cs', 'Czech'), ('ru', 'Russian'), ('pl', 'Polish'), ('hu', 'Hungarian'), ('fi', 'Finnish'), ('fa', 'Persian'), ('el', 'Greek'), ('tr', 'Turkish'), ('da', 'Danish'), ('he', 'Hebrew'), ('vi', 'Vietnamese'), ('ko', 'Korean'), ('ur', 'Urdu'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ca', 'Catalan'), ('ml', 'Malayalam'), ('no', 'Norwegian Bokmål'), ('nn', 'Norwegian Nynorsk'), ('other', 'Other language')], default='de', help_text='Select the language associated with the media files.', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='make_available_on_platform',
            field=models.BooleanField(default=False, verbose_name='Make media files available on Oral-History.Digital'),
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='replace_existing_files',
            field=models.BooleanField(default=False, verbose_name='Replace existing media files on Oral-History.Digital'),
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='transcribe',
            field=models.BooleanField(default=False, verbose_name='Transcribe media files automatically'),
        ),
    ]
