# Generated by Django 5.2.8 on 2025-11-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_alter_processingrequest_check_media_files_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.TextField(blank=True, default="", verbose_name="Label"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("de", "German"),
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("ja", "Japanese"),
                            ("zh", "Chinese"),
                            ("nl", "Dutch"),
                            ("uk", "Ukrainian"),
                            ("pt", "Portuguese"),
                            ("ar", "Arabic"),
                            ("cs", "Czech"),
                            ("ru", "Russian"),
                            ("pl", "Polish"),
                            ("hu", "Hungarian"),
                            ("fi", "Finnish"),
                            ("fa", "Persian"),
                            ("el", "Greek"),
                            ("tr", "Turkish"),
                            ("da", "Danish"),
                            ("he", "Hebrew"),
                            ("vi", "Vietnamese"),
                            ("ko", "Korean"),
                            ("ur", "Urdu"),
                            ("te", "Telugu"),
                            ("hi", "Hindi"),
                            ("ca", "Catalan"),
                            ("ml", "Malayalam"),
                            ("no", "Norwegian Bokmål"),
                            ("nn", "Norwegian Nynorsk"),
                            ("other", "Other language"),
                        ],
                        default="de",
                        help_text="Select the language of the transcript.",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        related_query_name="transcript",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "transcript",
                "verbose_name_plural": "transcripts",
                "ordering": ["-created_at"],
            },
        ),
    ]
