# Generated by Django 5.2.8 on 2025-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='content',
            field=models.JSONField(default=dict, help_text='Paste in the whole transcript in JSON format.', verbose_name='Content'),
        ),
    ]
