# Generated by Django 5.2.8 on 2025-11-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_transcript_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Label"
            ),
        ),
    ]
