# Generated by Django 5.2.8 on 2025-12-02 10:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_alter_transcript_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingrequest",
            name="admin_comment",
            field=tinymce.models.HTMLField(
                blank=True,
                default="",
                help_text="Optional comment by the administrator reviewing this request.",
                verbose_name="Admin comment",
            ),
        ),
    ]
