# Generated by Django 6.0.1 on 2026-01-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0023_alter_processingrequest_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created'),
                    ('accepted', 'Started'),
                    ('rejected', 'Rejected'),
                    ('completed', 'Completed'),
                ],
                default='created',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
