# Generated by Django 6.0.6 on 2026-06-16 20:34

import mmt.projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0024_alter_processingrequest_status_delete_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(
                max_length=128,
                validators=[mmt.projects.validators.validate_filename_safe],
                verbose_name='Title',
            ),
        ),
    ]
