# Generated by Django 6.0.7 on 2026-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
