# Generated by Django 6.0.8 on 2026-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='downloadable_files_count',
            field=models.IntegerField(default=0, help_text='Cache field for number of files in download directory.', verbose_name='Downloads'),
        ),
    ]
