# Generated by Django 6.0.8 on 2026-09-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0028_alter_project_downloadable_files_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processingrequest',
            name='one_action_checked',
        ),
        migrations.AddConstraint(
            model_name='processingrequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('check_media_files', True),
                    ('make_available_on_platform', True),
                    ('replace_existing_files', True),
                    ('transcribe', True),
                    _connector='OR',
                ),
                name='one_action_checked',
                violation_error_message='At least one action must be checked.',
            ),
        ),
    ]
