# Generated by Django 6.0.8 on 2026-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_project_downloadable_files_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processingrequest',
            name='one_action_checked',
        ),
        migrations.RenameField(
            model_name='processingrequest',
            old_name='make_available_on_platform',
            new_name='make_available_on_ohd',
        ),
        migrations.AddConstraint(
            model_name='processingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('make_available_on_ohd', True), ('replace_existing_files', True), ('check_media_files', True), ('transcribe', True), _connector='OR'), name='one_action_checked', violation_error_message='At least one action must be checked.'),
        ),
    ]
