# Generated by Django 6.0.8 on 2026-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_remove_processingrequest_one_action_checked_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processingrequest',
            name='one_action_checked',
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='align_transcripts',
            field=models.BooleanField(default=False, verbose_name='Align existing transcripts with media files'),
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='make_available_on_avd',
            field=models.BooleanField(default=False, verbose_name='Make media files available on Audio-Visual.Digital'),
        ),
        migrations.AddConstraint(
            model_name='processingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('make_available_on_ohd', True), ('make_available_on_avd', True), ('replace_existing_files', True), ('check_media_files', True), ('transcribe', True), ('align_transcripts', True), _connector='OR'), name='one_action_checked', violation_error_message='At least one action must be checked.'),
        ),
    ]
