# Generated by Django 6.0.8 on 2026-09-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0029_remove_processingrequest_one_action_checked_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processingrequest',
            name='one_action_checked',
        ),
        migrations.RenameField(
            model_name='processingrequest',
            old_name='make_available_on_platform',
            new_name='make_available_on_ohd',
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='replace_existing_files',
            field=models.BooleanField(
                default=False,
                verbose_name='Replace existing media files on the selected platforms',
            ),
        ),
        migrations.AddConstraint(
            model_name='processingrequest',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('check_media_files', True),
                    ('make_available_on_ohd', True),
                    ('replace_existing_files', True),
                    ('transcribe', True),
                    _connector='OR',
                ),
                name='one_action_checked',
                violation_error_message='At least one action must be checked.',
            ),
        ),
    ]
