# Generated by Django 5.1.6 on 2025-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Full name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="locale",
            field=models.CharField(
                choices=[("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
                verbose_name="Locale",
            ),
        ),
    ]
