# Generated by Django 5.2.3 on 2025-06-18 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Full name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
