# Generated by Django 5.2.3 on 2025-06-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_account", "0003_tag_user_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                help_text="Tags that describe or group the user",
                related_name="users",
                to="my_account.tag",
                verbose_name="Tags",
            ),
        ),
    ]
