# Generated by Django 5.2.6 on 2025-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0004_alter_user_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe or group the user', related_name='users', to='my_account.tag', verbose_name='Tags'),
        ),
    ]
