# Generated by Django 6.0.3 on 2026-04-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terms accepted at'),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Accepted terms version'),
        ),
    ]
