# Generated by Django 6.0.4 on 2026-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_account', '0009_profile_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='terms_accepted_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='terms_accepted_version',
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Terms accepted at'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_version',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='Accepted terms version'
            ),
        ),
    ]
