# Generated by Django 6.0.4 on 2026-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_account', '0010_remove_profile_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dpa_accepted_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the user accepted the Data Processing Agreement.',
                null=True,
                verbose_name='DPA accepted at',
            ),
        ),
    ]
