# Generated by Django 6.0.4 on 2026-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_account', '0011_user_dpa_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dpa',
            field=models.FileField(
                blank=True,
                help_text="Upload the user's data processing agreement here as a PDF file.",
                upload_to='dpas/',
                verbose_name='Data processing agreement',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='dpa_accepted_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the user accepted the Data Processing Agreement.',
                null=True,
                verbose_name='DPA date',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the user accepted the terms of use.',
                null=True,
                verbose_name='Terms date',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted_version',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='The latest terms of use version the user has accepted.',
                null=True,
                verbose_name='Terms version',
            ),
        ),
    ]
