# Generated by Django 6.0.4 on 2026-04-27 08:07

import mmt.my_account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_account', '0012_profile_dpa_alter_user_dpa_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dpa',
            field=models.FileField(
                blank=True,
                help_text="Upload the user's data processing agreement here as a PDF file.",
                upload_to=mmt.my_account.models.user_directory_path,
                verbose_name='Data processing agreement',
            ),
        ),
    ]
