# Generated by Django 6.0.5 on 2026-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_account', '0013_alter_profile_dpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feature_flags',
            field=models.JSONField(
                blank=True, default=dict, verbose_name='Feature flags'
            ),
        ),
    ]
