# Generated by Django 6.0.6 on 2026-06-05 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_account', '0014_profile_feature_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='feature_flags',
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[('chunked_upload', 'Chunked upload')],
                        max_length=50,
                        verbose_name='Name',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feature_flags',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Feature flag',
                'verbose_name_plural': 'Feature flags',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'name'), name='unique_user_flag'
                    )
                ],
            },
        ),
    ]
