# Generated by Django 6.0.7 on 2026-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0015_feature_flag_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
