# Generated by Django 6.0.8 on 2026-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0018_backfill_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(choices=[('chunked_upload', 'Chunked upload'), ('dummy', 'Dummy')], max_length=50, verbose_name='Name'),
        ),
    ]
