# Generated by Django 6.0.8 on 2026-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_account', '0019_alter_featureflag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(
                choices=[('dummy', 'Dummy')], max_length=50, verbose_name='Name'
            ),
        ),
    ]
