# Generated by Django 5.2.8 on 2025-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_de', models.CharField(max_length=255, verbose_name='Title (German)')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='Content (English)')),
                ('content_de', models.TextField(blank=True, default='', verbose_name='Content (German)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
