# Generated by Django 5.2.8 on 2025-12-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the notice should be shown on the welcome page.",
                verbose_name="active",
            ),
        ),
    ]
