# Generated by Django 5.2.9 on 2025-12-02 16:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_notice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content_de',
            field=tinymce.models.HTMLField(
                blank=True, default='', verbose_name='Content (German)'
            ),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content_en',
            field=tinymce.models.HTMLField(
                blank=True, default='', verbose_name='Content (English)'
            ),
        ),
    ]
