# Generated by Django 5.1.6 on 2025-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploaded_files", "0002_alter_uploadedfile_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="checksum_client",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Client checksum"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="checksum_server",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Server checksum"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="filename",
            field=models.CharField(max_length=255, verbose_name="Filename"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="media_type",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Media type"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="size",
            field=models.BigIntegerField(default=0, verbose_name="Size"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="transferred",
            field=models.BigIntegerField(default=0, verbose_name="Transferred"),
        ),
    ]
