name: App Tests

on:
  push:
    branches:
      - master
    paths:
      - "app/**"
  pull_request:
    paths:
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: test
      VITE_DEV_MODE: false
      SECRET_KEY: test-secret-key
      DATABASE_NAME: mmt
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_URL: mysql://root:root@127.0.0.1/mmt
      EMAIL_URL: dummymail://
      EMAIL_FROM: bob@example.com
      CELERY_BROKER_URL: redis://localhost

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mmt
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: Install the lastest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true
      - name: Install system dependencies
        run: |
          sudo apt-get install \
            --assume-yes \
            --no-install-recommends \
            --quiet \
            ffmpeg \
            gettext \
            libharfbuzz-subset0 \
            libpango-1.0-0 \
            libpangoft2-1.0-0
      - name: Create upload temp directories
        working-directory: ./app
        run: |
          mkdir --parents user_files/_tmp
          mkdir --parents user_files_test/_tmp
      - name: Build assets with Node.js
        working-directory: ./app
        run: |
          npm ci
          npm run build
      - name: Prepare Django installation
        working-directory: ./app
        run: |
          uv sync --group dev
          uv run manage.py compilemessages --verbosity 0
          uv run manage.py collectstatic --no-input --verbosity 0
      - name: Run Django tests
        working-directory: ./app
        run: |
          echo "Django $(uv run django-admin --version)"
          uv run pytest --ignore=mmt/core/tests/test_selenium.py --ignore=mmt/projects/tests/test_selenium.py
      - name: Run Vitest tests
        working-directory: ./app
        run: npm test
