name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Copy config files
      working-directory: ./app
      run: |
        cp my.cnf.example my.cnf
    - name: Install Python Dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build assets with Node.js
      working-directory: ./app
      run: |
        npm install
        npm run build
    - name: Run Tests
      working-directory: ./app
      run: |
        python manage.py test
