name: Docker Image CI for GHCR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Login to Github Container Registry
        uses: actions/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push the image
        run : |
          docker build . --tag ghcr.io/marcaltmann/mmt-py:latest
          docker push ghcr.io/marcaltmann/mmt-py:latest
